Vessels/Models/ErrorViewModel.cs
namespace Vessels.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vessels/Models/MessageModel.cs
namespace Vessels.Models
{
    public class MessageModel
    {
        public string IMO { get; set; }
        public string Name { get; set; }
        public DateTime DateTime { get; set; }
        public Position Position { get; set; }
    }

    public class Position
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}

Vessels/Controllers/API/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Net.WebSockets;
using Vessels.Data.Models;
using Vessels.Hubs;
using Vessels.Models;
using Vessels.Repositories;

namespace Vessels.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class MessageController : ControllerBase
    {
        private readonly IDataRepository dataRepository;
        private readonly IHubContext<VesselPositionsHub> hubContext;

        public MessageController(IDataRepository dataRepository, IHubContext<VesselPositionsHub> hubContext) 
        { 
            this.dataRepository = dataRepository;
            this.hubContext = hubContext;
        }


        [HttpPost]
        public async Task<IActionResult> Post([FromBody] MessageModel? message)
        {
            var vessel = await this.dataRepository.GetVesselAsync(message.IMO);
            if(vessel is not null && vessel.Name == message.Name) // check if data is valid
            {
                var position = new VesselPosition
                {
                    Date = message.DateTime,
                    Latitude = message.Position.Latitude,
                    Longitude = message.Position.Longitude,
                    VesselIMO = message.IMO,
                    Vessel = vessel,
                };
                await this.dataRepository.AddPositionAsync(position);

                position.Vessel.VesselPositions = null; //help ui to catch object(prevent cicle)
                await this.hubContext.Clients.All.SendAsync("ReceiveMessage", position);
                return Accepted();
            }
            return BadRequest();
        }
    }
}

Vessels/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Vessels.Data.Models;
using Vessels.Hubs;
using Vessels.Repositories;

namespace Vessels.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDataRepository dataRepository;
        private readonly IHubContext<VesselPositionsHub> hubContext;

        public HomeController(IDataRepository dataRepository, IHubContext<VesselPositionsHub> hubContext)
        {
            this.dataRepository = dataRepository;
            this.hubContext = hubContext;
        }

        // GET: Home
        public async Task<IActionResult> Index() => View(await this.dataRepository.GetAllPositionsAsync());

        // GET: Home/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) { return NotFound(); }

            var vesselPosition = await this.dataRepository.GetPositionAsync((int)id);
            if (vesselPosition is null) { return NotFound(); }

            return View(vesselPosition);
        }

        // GET: Home/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.VesselIMOs = await this.GetVessels();
            return View();
        }

        // POST: Home/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(nameof(VesselPosition.Id), nameof(VesselPosition.Date),
            nameof(VesselPosition.Latitude),nameof(VesselPosition.Longitude),nameof(VesselPosition.VesselIMO))] VesselPosition vesselPosition)
        {
            if (ModelState.IsValid) 
            {
                await this.dataRepository.AddPositionAsync(vesselPosition);
                var createdPosition = await dataRepository.GetPositionAsync(vesselPosition.Id);
                if(createdPosition is not null)
                {
                    createdPosition.Vessel.VesselPositions = null;
                    await this.hubContext.Clients.All.SendAsync("ReceiveMessage", createdPosition);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.VesselIMOs = await this.GetVessels();
            return View(vesselPosition);
        }

        // GET: Home/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) { return NotFound(); }

            var vesselPosition = await this.dataRepository.GetPositionAsync((int)id);
            if (vesselPosition is null) { return NotFound(); }
            ViewBag.VesselIMOs = await this.GetVessels();
            return View(vesselPosition);
        }

        // POST: Home/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind(nameof(VesselPosition.Id), nameof(VesselPosition.Date),
            nameof(VesselPosition.Latitude),nameof(VesselPosition.Longitude),nameof(VesselPosition.VesselIMO))] VesselPosition vesselPosition)
        {
            if (id != vesselPosition.Id) { return NotFound(); }

            if (ModelState.IsValid)
            {
                try { await this.dataRepository.UpdatePositionAsync(vesselPosition); }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VesselPositionExists(vesselPosition.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.VesselIMOs = await this.GetVessels();
            return View(vesselPosition);
        }

        // GET: Home/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) { return NotFound(); }

            var vesselPosition = await this.dataRepository.GetPositionAsync((int)id);
            if (vesselPosition is null) { return NotFound(); }

            return View(vesselPosition);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vesselPosition = await this.dataRepository.GetPositionAsync((int)id);
            if (vesselPosition is not null) { await this.dataRepository.DeletePositionAsync(id); }
            
            return RedirectToAction(nameof(Index));
        }

        private bool VesselPositionExists(int id) => this.dataRepository.PositionExists(id);

        private async Task<SelectList> GetVessels() => new SelectList(await this.dataRepository.GetVesselsAsync(), nameof(Vessel.IMO), nameof(Vessel.Name));

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            this.dataRepository.Dispose();
        }
    }
}

Vessels/Controllers/VesselsController.cs
using Microsoft.AspNetCore.Mvc;
using Vessels.Repositories;

namespace Vessels.Controllers
{
    public class VesselsController : Controller
    {
        private readonly IDataRepository dataRepository;

        public VesselsController(IDataRepository dataRepository) => this.dataRepository = dataRepository;

        // GET: Home
        public async Task<IActionResult> Index() => View(await this.dataRepository.GetVesselsAsync());
    }
}

Vessels/Views/Home/Create.cshtml
@model Vessels.Data.Models.VesselPosition

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>VesselPosition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VesselIMO" class="control-label"></label>
                <select asp-for="VesselIMO" class ="form-control" asp-items="ViewBag.VesselIMOs"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vessels/Views/Home/Delete.cshtml
@model Vessels.Data.Models.VesselPosition

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VesselPosition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Vessels/Views/Home/Details.cshtml
@model Vessels.Data.Models.VesselPosition

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VesselPosition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vessel!.IMO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vessel!.IMO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vessel!.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vessel!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Vessels/Views/Home/Edit.cshtml
@model Vessels.Data.Models.VesselPosition

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>VesselPosition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VesselIMO" class="control-label"></label>
                <select asp-for="VesselIMO" class="form-control" asp-items="ViewBag.VesselIMOs"></select>
                <span asp-validation-for="VesselIMO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vessels/Views/Home/Index.cshtml
@model IEnumerable<Vessels.Data.Models.VesselPosition>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vessel!.IMO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vessel!.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="table-body">
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vessel!.IMO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vessel!.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |                
                <a target=”_blank” href="https://www.google.com/maps/search/?api=1&query=@item.Latitude,@item.Longitude">Google Maps</a>
            </td>
        </tr>
}
    </tbody>
</table>

<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/positions.js"></script>

Vessels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vessel Postions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vessels.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vessel Positions</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vessels" asp-action="Index">Vessels</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Vessel Postions
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vessels/Views/Vessels/Index.cshtml
@model IEnumerable<Vessels.Data.Models.Vessel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IMO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IMO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
}
    </tbody>
</table>